---

# Playbook: sentinel xwiki
# Author: Shahriar Shafiullah
# Date: 03-08-2015
# Description: Creates LXC containers and installs Xwiki on top of a tomcat7 and Postgressql stack

- hosts: sentinel 
  user: sshafiullah
  sudo: yes
  sudo_user: root 

  tasks:
    - name: install tomcat7
      apt:
        name: tomcat7 
        update_cache: yes 
        state: installed

    - name: create setenv.sh file
      copy:
        src: tomcat/setenv.sh
        dest: /usr/share/tomcat7/bin/setenv.sh
      notify: restart tomcat
    
    - name: change attributes on setenv.sh
      file:
        path: /usr/share/tomcat7/bin/setenv.sh
        owner: root
        group: tomcat7
        mode:  0755
      notify: restart tomcat

    - name: install postgres JDBC library
      get_url:
        dest: /usr/share/tomcat7/lib/postgresql-9.4-1201.jdbc4.jar
        url: https://jdbc.postgresql.org/download/postgresql-9.4-1201.jdbc4.jar
        validate_certs: no
        force: no


# Postgres database installation

    - name: Install postgres database
      apt:
        name: postgresql-9.3
        state: installed

    - name: Give ansible permission to access postgres
      copy:
        src: postgres/pg_hba.conf
        dest: /etc/postgresql/9.3/main/pg_hba.conf

    - name: Set appropriate permissions on pg_hba.conf
      file:
        path: /etc/postgresql/9.3/main/pg_hba.conf
        owner: postgres 
        group: postgres
        mode: 0640

    - name: Reload postgres configurations
      shell: /usr/bin/service postgresql restart; /usr/bin/touch /opt/postgres
      args:
        creates: /opt/postgres

#    - name: Install psycopg2
#      apt:
#        name: python-psycopg2
#        state: installed
    
#    - name: Create xwiki database
#      postgresql_db: 
#        name: xwiki
#        encoding: 'UTF-8'
#        login_host: localhost
#        login_user: postgres
#        login_password: md501189ab90a12af0753fd0b06d9f22a90
#        state: present
#        owner: postgres
      
#    - name: Create xwiki user
#      postgresql_user:
#        name: xwiki
#        db: xwiki
#        priv: ALL 
#        password: md501189ab90a12af0753fd0b06d9f22a90
#        encrypted: yes 

    - name: Create DB sql script
      copy:
        src: postgres/xwiki.sql
        dest: /opt/xwiki.sql
      
    - name: Create xwiki DB and user
      shell: /usr/bin/psql -U postgres -f /opt/xwiki.sql; /usr/bin/touch /opt/xwiki 
      args:
        creates: /opt/xwiki 
# Deploy the Xwiki application

    - name: Download Xwiki war file
      get_url:
        dest: /opt/xwiki-enterprise-web-7.1.2-20150725.161333-26.war
        url: http://maven.xwiki.org/snapshots/org/xwiki/enterprise/xwiki-enterprise-web/7.1.2-SNAPSHOT/xwiki-enterprise-web-7.1.2-20150725.161333-26.war 
        force: no

    - name: create xwiki directory
      file:
        path: /var/lib/tomcat7/webapps/xwiki
        state: directory
        owner: tomcat7
        group: tomcat7
        
    - name: deploy xwiki
      command: /usr/bin/unzip /opt/xwiki-enterprise-web-7.1.2-20150725.161333-26.war
      args: 
        chdir: /var/lib/tomcat7/webapps/xwiki
        creates: /var/lib/tomcat7/webapps/xwiki/templates
      notify: restart tomcat

    - name: Configure hibernate file
      copy:
        src: tomcat/hibernate.cfg.xml
        dest: /var/lib/tomcat7/webapps/xwiki/WEB-INF/hibernate.cfg.xml
      notify: restart tomcat

  handlers:
    - name: restart tomcat
      action: service name=tomcat7 state=restarted 

